### ISSUE TITLE
Query fails with get_postgis_query but not dbGetQuery

### ISSUE THREAD

**Issue by zross** [SESYNC-ci/postGIStools#2]
I'm not in need of having this solved -- I have a work-around -- but I'm wondering why this line of code works:

`dbGetQuery(con, "SELECT 1 id, ST_AsText(ST_ConvexHull(ST_Collect(geom))) geom from grid90m")`

But this does not:

`postGIStools::get_postgis_query(con, "SELECT 1 id, ST_AsText(ST_ConvexHull(ST_Collect(geom))) geom from grid90m",  geom_name = "geom")`

**Comment by pmarchand1** [comment]
I now realize the documentation should have specified that the geom and/or hstore fields cannot be transformed and/or aliased in the query.

The reason is that get_postgis_query first does a find/replace to transform the query statement so that geoms are returned as WKT and hstores as JSON. For example, this query from the vignette example:

```
 countries <- get_postgis_query(con, "SELECT name, iso2, geom, translations 
      FROM country WHERE population > 1000000",
      geom_name = "geom", hstore_name = "translations")
```

actually gets sent as:

```
SELECT * FROM (
     SELECT name, iso2, ST_AsText("geom") AS "geom_wkt", ST_SRID("geom") AS "geom_srid",  
            hstore_to_json("translations") AS "translations_json" 
     FROM country WHERE population > 1000000) AS base_qry 
LEFT JOIN spatial_ref_sys ON "geom_srid" = srid
```

It seems adding the ability to process transformations in the query statement would require actually parsing the SQL to find which term to wrap ST_AsText around. One way to do pre-processing in SQL could be with a temp table or view, if user permissions allow it.

**Comment by zross** [comment]
Very interesting, thanks for letting me know!
